- hosts: OSEv3
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: 'install python Ubuntu/Debian'
    raw: 'sudo apt-get -y install python'
    when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
  - name: 'install python RedHat'
    raw: 'sudo yum -y install python'
    when: ansible_os_family == 'RedHat'

  tasks:
  - block: # --! Block for RPM Based OS !--
    - name: install EPEL
      yum: name="epel-release" state=installed
    - name: install PKGs
      yum: name="{{ item }}" state=installed
      loop:
      - docker
      - chrony
      - bash-completion
      - zabbix40-agent
      - iperf3
      - sysstat
      - smartmontools
      - lshw
      - hwinfo
      - net-tools
      - telnet
      - fio
      - hdparm
      - ipmitool
      - wget
      - jnettop
      - htop
      - pv
      - hping3
    when: ansible_os_family == "RedHat"

  - name: Make sure a service is running
    systemd:
    state: started
    name: "{{ item }}"
    with_items:
    - docker
    - chronyd
    - zabbix-agent
    - sysstat

  - name: enable service chronyd and ensure it is not masked
    systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    with_items:
    - docker
    - chronyd
    - zabbix-agent
    - sysstat

  - name: Stop and disable firewalld.
    service:
      name: firewalld
      state: stopped
      enabled: False

  - name: Disable SELinux
    selinux:
      state: disabled

